import { z } from "zod"
import { generateImageWithModelBodySchema } from "./image-models.schema.js"

// Task type enum
export const taskTypeSchema = z.enum([
  "generate_image",
  "generate_video",
  "image_upscale",
  "image_remove_background",
])

// Task status enum
export const taskStatusSchema = z.enum([
  "pending",
  "processing",
  "completed",
  "failed",
])

// Task body schemas (flexible JSONB)
// New multi-model image generation schema
export const generateImageBodySchema = generateImageWithModelBodySchema

export const generateVideoBodySchema = z.object({
  prompt: z.string().min(1).max(1000),
  aspectRatio: z.string().optional().default("16:9"),
  duration: z.number().optional().default(5),
  storageAssetId: z
    .string()
    .min(1)
    .describe(
      "Pre-generated storage ID for the asset (e.g., 'c7b3d8f0-ai-1699234567.mp4'). " +
        "Generated by frontend using uniqueId() to ensure consistent ID format with manual uploads."
    ),
})

export const upscaleImageBodySchema = z.object({
  sourceAssetId: z.string(),
  factor: z.union([z.literal(2), z.literal(4)]).default(4),
})

export const removeBackgroundBodySchema = z.object({
  sourceAssetId: z.string(),
})

// Task result schemas
export const taskResultSuccessSchema = z.object({
  assetId: z.string(),
  assetUrl: z.string().url(),
  metadata: z
    .object({
      width: z.number().optional(),
      height: z.number().optional(),
      fileSize: z.number().optional(),
      processingTime: z.number().optional(),
    })
    .passthrough()
    .optional(),
})

export const taskResultErrorSchema = z.object({
  errorMessage: z.string(),
  errorCode: z.string(),
  errorDetails: z
    .object({
      attempts: z.number().optional(),
      lastError: z.string().optional(),
    })
    .passthrough()
    .optional(),
})

// Task entity schema
export const taskSchema = z.object({
  id: z.string().uuid(),
  taskType: taskTypeSchema,
  userId: z.string(),
  projectId: z.string().uuid(),
  shapeId: z.string().nullable(),
  body: z.record(z.any()),
  status: taskStatusSchema,
  result: z.union([taskResultSuccessSchema, taskResultErrorSchema]).nullable(),
  retryCount: z.number(),
  maxRetries: z.number(),
  workerId: z.string().nullable(),
  claimedAt: z.string().datetime().nullable(),
  createdAt: z.string().datetime(),
  startedAt: z.string().datetime().nullable(),
  completedAt: z.string().datetime().nullable(),
  updatedAt: z.string().datetime(),
})

// API Request schemas

// POST /v1/tasks - Create task
export const createTaskRequestSchema = z.object({
  taskType: taskTypeSchema,
  projectId: z.string().uuid(),
  shapeId: z.string().optional(),
  body: z.record(z.any()),
})

// Response for task creation
export const createTaskResponseSchema = z.object({
  taskId: z.string().uuid(),
  taskType: taskTypeSchema,
  status: taskStatusSchema,
  createdAt: z.string().datetime(),
})

// GET /v1/tasks/:taskId - Get task status
export const getTaskResponseSchema = taskSchema

// GET /v1/tasks - List tasks
export const listTasksQuerySchema = z.object({
  projectId: z.string().uuid(),
  taskType: taskTypeSchema.optional(),
  status: z
    .union([taskStatusSchema, z.array(taskStatusSchema)])
    .optional()
    .transform((val) => {
      if (typeof val === "string") return val
      if (Array.isArray(val)) return val.join(",")
      return undefined
    }),
  limit: z
    .string()
    .optional()
    .transform((v) => (v ? parseInt(v, 10) : 50)),
  offset: z
    .string()
    .optional()
    .transform((v) => (v ? parseInt(v, 10) : 0)),
})

export const listTasksResponseSchema = z.object({
  tasks: z.array(taskSchema),
  total: z.number().optional(),
})

// DELETE /v1/tasks/:taskId - Cancel task
export const cancelTaskResponseSchema = z.object({
  success: z.boolean(),
})

// Type exports
export type TaskType = z.infer<typeof taskTypeSchema>
export type TaskStatus = z.infer<typeof taskStatusSchema>
export type GenerateImageBody = z.infer<typeof generateImageBodySchema>
export type GenerateVideoBody = z.infer<typeof generateVideoBodySchema>
export type UpscaleImageBody = z.infer<typeof upscaleImageBodySchema>
export type RemoveBackgroundBody = z.infer<typeof removeBackgroundBodySchema>
export type TaskResultSuccess = z.infer<typeof taskResultSuccessSchema>
export type TaskResultError = z.infer<typeof taskResultErrorSchema>
export type Task = z.infer<typeof taskSchema>
export type CreateTaskRequest = z.infer<typeof createTaskRequestSchema>
export type CreateTaskResponse = z.infer<typeof createTaskResponseSchema>
export type GetTaskResponse = z.infer<typeof getTaskResponseSchema>
export type ListTasksQuery = z.infer<typeof listTasksQuerySchema>
export type ListTasksResponse = z.infer<typeof listTasksResponseSchema>
export type CancelTaskResponse = z.infer<typeof cancelTaskResponseSchema>
